# chaine prefixe du chemin vers les graphes
inputGraphPrefix: "/Volumes/LILI/donnees/francais/2012_nofilter/gexf-24h/gexf-24h/fran_sans4080_03_31_"

# ?
nbRoamingBTSmoy: "./ressources/nb_roam_bts_moy.csv"

# chemin de sortie des captures (préfixe)
capturesPrefix: "./captures/touristflows31-March-2009-num_"


# icone utilise pour la heatmap
heatMapSprite: "./ressources/ppp.png"

# ATTENTION aux espaces !
arrowsPrefix: "./ressources/Arrow31 March 2009 "

# attention.. aux.. espaces..
writeArrowsPrefix: "./Arrow roaming "

# set to true to enable proxy
useProxy: false
proxyHost: p-goodway.rd.francetelecom.fr
proxyPort: 3128


# initial camera position
initialLat: 48.866
initialLon: 2.359

# camera zoom settings
initialZoom: 10
minZoom: 9
maxZoom: 14

# screen resolution
screenWidth: 1200
screenHeight: 900

# fond de carte: si useMBTiles est vrai, alors cela utilise le fichier de fond de cartes
useTiles: true
pathToTiles: "jdbc:sqlite:./ressources/idf_light.mbtiles"