# chaine prefixe du chemin vers les graphes
# prefixe
# Prefixe.
# PREFIXE
# ok?
inputGraphPrefix: "/Users/jfenchong/Documents/these/données/gexf_roam/roaming_03_31_"

# ?
nbRoamingBTSmoy: "/Users/jfenchong/Documents/these/données/nb_roam_03_31.csv"

# separateur de colonnes pour le csv "nbRoamingBTSmoy"
roamingBTScsvSeparator: ";"

# chemin de sortie des captures (préfixe) quand on appuie sur 's'
capturesPrefix: "./captures/tourist_flows-31-March-2009_"

# chemin de sortie des captures "video" (préfixe) quand on appuie sur 'f'
capturesVideoPrefix: "./captures/video/video_tourist_flows-31-March-2009-"

# images par seconde
videoFramerate: 2

# qualite de la video - devrait rester a 1800 normalement
videoBitrate: 1200

# supprimer automatiquement les captures apres la video ?
supprimerCapturesApresVideo: false


# icone utilise pour la heatmap
heatMapSprite: "./ressources/ppp.png"

# ATTENTION aux espaces !
arrowsPrefix: "./ressources/Arrow31 March 2009 "

# attention.. aux.. espaces..
writeArrowsPrefix: "./Arrow roaming "

# creer fleches depuis oursins?
# d'apres quentin:
# mettre a true si l'on veut creer les fleches depuis les oursins
# sinon mettre false, et ca va charger des fichiers csv deja prepares
createArrowsFromUrchins: true

# set to true to enable proxy
useProxy: false
proxyHost: p-goodway.rd.francetelecom.fr
proxyPort: 3128


# initial camera position
initialLat: 48.866
initialLon: 2.359

# camera zoom settings
initialZoom: 10
minZoom: 9
maxZoom: 14

# screen resolution
screenWidth: 1200
screenHeight: 900

# non utilise
#heatmapFromColor: [255, 255, 255]
#heatmapFromColor: [189, 73, 50]

# fond de carte: si useMBTiles est vrai, alors cela utilise le fichier de fond de cartes
useTiles: true
pathToTiles: "jdbc:sqlite:/Users/jfenchong/Documents/MapBox/export/idf_toprint.mbtiles"